/* Configuration for dining_philosophers generated by Alire */
#ifndef DINING_PHILOSOPHERS_CONFIG_H
#define DINING_PHILOSOPHERS_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "dining_philosophers"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
